export const themes = [
  { id: "modern", name: "Modern Design", description: "Clean, Swiss typography, subtle shadows" },
  { id: "brutalism", name: "Brutalism", description: "Harsh, unpolished, zero-radius, heavy borders" },
  { id: "glassmorphism", name: "Glassmorphism", description: "Frosted glass, blurred backdrops, translucency" },
  { id: "cyberpunk", name: "Cyberpunk UI", description: "Neon glows, dark backgrounds, tech-focused" },
  { id: "neumorphism", name: "Neumorphism", description: "Soft extruded plastic, low contrast UI" },
  { id: "claymorphism", name: "Claymorphism", description: "Soft, friendly 3D clay-like surfaces" },
  { id: "aurora", name: "Aurora UI", description: "Soft blurry gradient backgrounds" },
  { id: "retrofuturism", name: "Retro-Futurism", description: "Vintage meets future tech" },
  { id: "bento", name: "Bento Box Grid", description: "Strict partitioned layouts, clean lines" },
  { id: "spatial", name: "Spatial UI (VisionOS)", description: "Extreme glassmorphism, dynamic lighting, pill shapes" },
  { id: "terminal", name: "Terminal / CLI", description: "Hacker aesthetic, pure black, glowing green" },
  { id: "wireframe", name: "Wireframe", description: "Architectural blueprint, blue monospace" },
  { id: "amoled", name: "AMOLED Pitch Black", description: "Battery-saver ultra dark mode, zero shadow" },
  { id: "holographic", name: "Holographic", description: "Iridescent vibes, cyan and magenta mesh" },
  { id: "dracula", name: "Dracula", description: "Deep purple/grey background, pink/cyan accents" },
  { id: "nord", name: "Nord", description: "Arctic, cold, and clean. Pale blue-greys" },
  { id: "solarized-light", name: "Solarized Light", description: "Warm, eye-friendly retro beige" },
  { id: "solarized-dark", name: "Solarized Dark", description: "Deep teal backgrounds, eye-friendly" },
  { id: "bauhaus", name: "Bauhaus", description: "1920s architecture, geometric, primary colors" },
  { id: "hand-drawn", name: "Hand-drawn / Sketch", description: "Marker/pen aesthetic, rough borders" },
  { id: "comic", name: "Comic Book / Pop Art", description: "Halftone backgrounds, bold black borders" },
  { id: "watercolor", name: "Watercolor", description: "Soft bleeding edges, pastel hues" },
  { id: "candy", name: "Candy / Bubblegum", description: "Playful, bright pinks, massive radiuses" },
  { id: "material", name: "Material Design 3", description: "Google's modern aesthetic, adaptive colors" },
  { id: "voice", name: "Voice-First Multimodal", description: "Deep dark gradients, pulsing shadows" },
  { id: "cursor", name: "Interactive Cursor-Focused", description: "Minimalist base for custom cursors" },
  { id: "aqua", name: "macOS Aqua", description: "Retro 2000s Apple, glossy pills" },
  { id: "fluent", name: "Fluent Design", description: "Windows 11 style, mica material" },
  { id: "cyber-noir", name: "Cyber-Noir", description: "Blade Runner vibes, dark rainy greys" },
  { id: "monochrome-brutalism", name: "Monochrome Brutalism", description: "Greyscale, thick borders, harsh" },
  { id: "flat-design", name: "Flat Design", description: "2D minimalist, solid colors, icon-heavy" },
  { id: "skeuomorphism", name: "Skeuomorphism", description: "Realistic textures, 3D depth, material" },
  { id: "liquid-glass", name: "Liquid Glass", description: "Flowing fluid effects, iridescent blur" },
  { id: "hero-centric", name: "Hero-Centric", description: "Dramatic visuals, high-contrast CTA" },
  { id: "conversion", name: "Conversion-Optimized", description: "Urgency elements, single focus CTA" },
  { id: "feature-rich", name: "Feature-Rich Showcase", description: "Grid benefits, interactive visual demos" },
  { id: "minimal-direct", name: "Minimal & Direct", description: "Max white space, essential typography" },
  { id: "social-proof", name: "Social Proof", description: "Testimonials prominent, credibility markers" },
  { id: "interactive-demo", name: "Interactive Demo", description: "Embedded walkthroughs, step guides" },
  { id: "trust-authority", name: "Trust & Authority", description: "Certificates, expert credentials, security" },
  { id: "storytelling", name: "Storytelling-Driven", description: "Narrative flow, visual journey progression" },
  { id: "data-dense", name: "Data-Dense Dashboard", description: "Space-efficient grid, maximum data visibility" },
  { id: "heatmap", name: "Heat Map Style", description: "Color-coded intensity, geographical data" },
  { id: "hyperrealism-3d", name: "3D Hyperrealism", description: "Tactile details, spatial 3D elements" },
  { id: "vibrant-block", name: "Vibrant Block", description: "Bold geometric shapes, playful high contrast" },
  { id: "accessible", name: "Accessible & Ethical", description: "WCAG AAA, high contrast, symbol focus" },
  { id: "motion-driven", name: "Motion-Driven", description: "Animation-heavy, parallax, microinteractions" },
  { id: "zero-ui", name: "Zero Interface", description: "Minimal visible controls, context-aware ambient" }
] as const;

export type ThemeId = typeof themes[number]["id"];
